/**
 * Extracts \newcommand definitions from the LaTeX template's macros.tex into a
 * KaTeX macro map, so the shorthands used throughout the .tex notes
 * (\bbR, \eps, \bs{...}, ...) render in the app. Regenerate after editing
 * templates/latex/macros.tex:  npx tsx scripts/gen-katex-macros.ts
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
// letterfonts.tex holds the \bbR/\mcX-style shorthands; macros.tex the rest.
const SRCS = ["macros.tex", "letterfonts.tex", "preamble.tex"].map((f) => join(ROOT, "templates", "latex", f));
const OUT = join(ROOT, "lib", "katexMacros.ts");

const macros: Record<string, string> = {};

for (const SRC of SRCS) {
  if (!existsSync(SRC)) continue;
  const text = readFileSync(SRC, "utf8");
  // \newcommand{\name}[argc]{body} — brace-matched body, comments stripped
  const re = /\\(?:re)?newcommand\*?\s*\{\s*\\([a-zA-Z]+)\s*\}\s*(?:\[(\d+)\])?\s*\{/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) {
    const [, name, argc] = m;
    let depth = 1;
    let i = re.lastIndex;
    let body = "";
    while (i < text.length && depth > 0) {
      const ch = text[i];
      if (ch === "\\") {
        body += text[i] + (text[i + 1] ?? "");
        i += 2;
        continue;
      }
      if (ch === "{") depth++;
      else if (ch === "}") {
        depth--;
        if (depth === 0) break;
      }
      body += ch;
      i++;
    }
    if (depth !== 0) continue;
    const clean = body.replace(/(^|[^\\])%.*$/gm, "$1").trim();
    if (!clean) continue;
    // KaTeX rejects definitions referencing unsupported primitives; those simply
    // fall back to rendering the raw command, so keeping them is harmless.
    macros[`\\${name}`] = argc ? clean : clean;
  }
}

const banner = `// GENERATED by scripts/gen-katex-macros.ts from templates/latex/macros.tex — do not edit by hand.\n`;
writeFileSync(
  OUT,
  banner +
    `export const KATEX_MACROS: Record<string, string> = ${JSON.stringify(macros, null, 2)};\n`,
);
console.log(`katexMacros.ts: ${Object.keys(macros).length} macro(s)`);
